cleaned up the script so that all teh checks are in one place

diff --git a/deploy/build_docker_image b/deploy/build_docker_image
--- a/deploy/build_docker_image
+++ b/deploy/build_docker_image
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+MAGENTA=`tput setaf 5`
+GREEN=`tput setaf 2`
+BOLD=`tput bold`
+PLAIN=`tput sgr0`
+
 VERSION_LABEL=ellipsis-`git rev-parse --short HEAD`
 PUBLIC_ASSETS_DIR=/tmp/public-assets
 
@@ -17,7 +22,17 @@ if [ "$1" = "stag01" ]; then
   AWS_ELLIPSIS_PROFILE="el-stag01-${STAG01_ACCOUNT_ID}"
 fi
 
-printf "\n\n Deploying to ${TARGET_ENV} \n\n"
+printf "\n\n${GREEN}Deploying to ${MAGENTA}${TARGET_ENV}${PLAIN}\n\n"
+
+printf "${GREEN}Checking your local branch...${PLAIN}\n"
+pushd `git rev-parse --show-toplevel` > /dev/null
+git diff-index --quiet HEAD --
+if [ $? -eq 1 ];then
+  printf "\n\n${GREEN}You have uncommitted changes in your working directory.\n"
+  printf "Deal with them first!${PLAIN}\n\n";
+  # exit 1
+fi
+printf "Done.\n"
 
 hold_on_to_your_butts() {
   printf "\e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[38;5;52m1\e[38;5;52m0\e[38;5;52m1\e[38;5;52m1\e[38;5;138m0\e[38;5;145m0\e[38;5;52m1\e[0m \e[0m \e[38;5;53m0\e[38;5;139m1\e[38;5;231m1\e[38;5;231m1\e[38;5;231m0\e[38;5;231m1\e[38;5;231m1\e[38;5;225m0\e[38;5;181m1\e[0m \e[0m \e[0m \e[0m \e[0m \e[0m \e[38;5;17m1\e[38;5;24m0\e[0m \e[0m \e[38;5;17m0\e[38;5;17m1\e[38;5;17m1\e[0m
@@ -51,28 +66,11 @@ hold_on_to_your_butts() {
   printf "Hold on to your butts...\n"
 }
 
-MAGENTA=`tput setaf 5`
-GREEN=`tput setaf 2`
-BOLD=`tput bold`
-PLAIN=`tput sgr0`
-
+printf "${GREEN}Checking your Environment...${PLAIN}\n"
 if [ -z "$ELLIPSIS_DEPLOY_TOKEN" ];then
-  printf "${GREEN}You need to set the ELLIPSIS_DEPLOY_TOKEN environment \
-        variable. Visit https://bot.ellipsis.ai/list_api_tokens and add
-        the deploy token to your environment.${PLAIN}"
-  exit 1
-fi
-
-GIT_USERNAME=`git config user.name`
-DISPLAY_USERNAME=${GIT_USERNAME:-$USER}
-printf "${GREEN}Announcing the deployment to #dev...${PLAIN}"
-curl -f --data "message=Heads%20up!%20${DISPLAY_USERNAME}%20is%20preparing%20a%20deploy%20to%20${TARGET_ENV}.&responseContext=slack&channel=dev&token=${ELLIPSIS_DEPLOY_TOKEN}" https://bot.ellipsis.ai/api/say || (printf "${GREEN}The deploy announcement failed. Please check the ELLIPSIS_DEPLOY_TOKEN environment variable.${PLAIN}" && exit 1)
-printf "\n"
-pushd `git rev-parse --show-toplevel` > /dev/null
-git diff-index --quiet HEAD --
-if [ $? -eq 1 ];then
-  printf "\n\n${GREEN}You have uncommitted changes in your working directory.\n"
-  printf "Deal with them first!${PLAIN}\n\n";
+  printf "${GREEN}You need to set the ELLIPSIS_DEPLOY_TOKEN environment variable.\n"
+  printf "Visit https://bot.ellipsis.ai/list_api_tokens and add"
+  printf "the deploy token to your environment.${PLAIN}"
   exit 1
 fi
 
@@ -95,8 +93,46 @@ type activator >/dev/null 2>&1 || {
   exit 1
 }
 
-printf "Running eslint...\n"
+if ! type aws > /dev/null;then
+  printf "\n\nYou need to set up the aws CLI tools.\n"
+  printf "Try ${GREEN}brew install awscli${PLAIN} if you’re using brew,\n"
+  printf "or go to ${GREEN}https://aws.amazon.com/cli/${PLAIN}.\n";
+  exit 1
+if
+
+if [ -z ${AWS_ELLIPSIS_PROFILE+x} ];then
+  printf "You need to set the ${GREEN}AWS_ELLIPSIS_PROFILE${PLAIN}"
+  printf "env var with the profile to use for AWS.\n"
+  printf "
+1. If you haven’t already, run ${GREEN}aws configure --profile ellipsis${PLAIN} to set up a
+ profile.
+
+ You will need an AWS access key and secret key. If you don’t have one, you
+ can create a new one from the users page:
+
+ ${GREEN}https://console.aws.amazon.com/iam/home?region=us-east-1#users${PLAIN}
+
+ Use ${GREEN}text${PLAIN} for the output format, and ${GREEN}us-east-1${PLAIN} for the region.
+
+2. Add a line to your ${GREEN}.bashrc${PLAIN} file:
+
+ ${GREEN}export AWS_ELLIPSIS_PROFILE=ellipsis${PLAIN}
+
+3. Open a new terminal or run ${GREEN}source ~/.bashrc${PLAIN}, then try again.\n";
+exit 1
+fi
+
+printf "${GREEN}Done.${PLAIN}\n"
+
+printf "${GREEN}Announcing the deployment to #dev...${PLAIN}\n"
+GIT_USERNAME=`git config user.name`
+DISPLAY_USERNAME=${GIT_USERNAME:-$USER}
+curl -f --data "message=Heads%20up!%20${DISPLAY_USERNAME}%20is%20preparing%20a%20deploy%20to%20${TARGET_ENV}.&responseContext=slack&channel=dev&token=${ELLIPSIS_DEPLOY_TOKEN}" https://bot.ellipsis.ai/api/say || (printf "${GREEN}The deploy announcement failed. Please check the ELLIPSIS_DEPLOY_TOKEN environment variable.${PLAIN}" && exit 1)
+printf "\nDone.\n"
+
+printf "${GREEN}Running eslint...${PLAIN}\n"
 npm run lint
+printf "\nDone.\n"
 if [ $? -eq 1 ];then
   read -p "eslint failed. You should probably stop. Do you want to continue anyway? [y/N]: " -n 1 -r
   echo
@@ -108,8 +144,8 @@ if [ $? -eq 1 ];then
   fi
 fi
 
-printf "Running jest...\n"
-# npm test
+printf "${GREEN}Running jest...${PLAIN}\n"
+npm test
 if [ $? -eq 1 ];then
   printf "\n\n${BOLD}JavaScript tests failed.${PLAIN} You should probably stop.\n"
   read -p "Do you want to continue anyway? [y/N]: " -n 1 -r
@@ -121,8 +157,9 @@ if [ $? -eq 1 ];then
     hold_on_to_your_butts
   fi
 fi
+printf "\nDone.\n"
 
-printf "Running activator test...\n"
+printf "${GREEN}Running activator test...${PLAIN}\n"
 activator test
 if [ $? -eq 1 ];then
   printf "\n\n";
@@ -135,7 +172,9 @@ if [ $? -eq 1 ];then
     hold_on_to_your_butts
   fi
 fi
+printf "\nDone.\n"
 
+printf "${GREEN}Packaging the build...${PLAIN}\n";
 touch conf/version.conf
 echo application.version=\"`git rev-parse --short HEAD`\" >conf/version.conf
 activator docker:stage
@@ -147,50 +186,25 @@ BUNDLE=$VERSION_LABEL.zip
 BUNDLE_PATH=~/Desktop/$BUNDLE
 zip -qq -r $BUNDLE_PATH .
 popd > /dev/null
+printf "\nDone.\n"
 
+printf "${GREEN}Syncing assets with S3...${PLAIN}\n";
+mkdir -p $PUBLIC_ASSETS_DIR
+rm -rf $PUBLIC_ASSETS_DIR/*
+unzip -qq target/docker/stage/opt/docker/lib/ellipsis.ellipsis-1.0-SNAPSHOT-assets.jar -d $PUBLIC_ASSETS_DIR/
+aws --profile $AWS_ELLIPSIS_PROFILE s3 sync $PUBLIC_ASSETS_DIR/public s3://$ASSETS_BUCKET/ --acl=public-read --quiet
+printf "Done.\n";
 
-if ! type aws > /dev/null;then
-  printf "\n\nYou need to set up the aws CLI tools.\n"
-  printf "Try ${GREEN}brew install awscli${PLAIN} if you’re using brew,\n"
-  printf "or go to ${GREEN}https://aws.amazon.com/cli/${PLAIN}.\n";
-else
-  if [ -z ${AWS_ELLIPSIS_PROFILE+x} ];then
-    printf "You need to set the ${GREEN}AWS_ELLIPSIS_PROFILE${PLAIN}"
-    printf "env var with the profile to use for AWS.\n"
-    printf "
-1. If you haven’t already, run ${GREEN}aws configure --profile ellipsis${PLAIN} to set up a
-   profile.
-
-   You will need an AWS access key and secret key. If you don’t have one, you
-   can create a new one from the users page:
-
-   ${GREEN}https://console.aws.amazon.com/iam/home?region=us-east-1#users${PLAIN}
-
-   Use ${GREEN}text${PLAIN} for the output format, and ${GREEN}us-east-1${PLAIN} for the region.
-
-2. Add a line to your ${GREEN}.bashrc${PLAIN} file:
-
-   ${GREEN}export AWS_ELLIPSIS_PROFILE=ellipsis${PLAIN}
-
-3. Open a new terminal or run ${GREEN}source ~/.bashrc${PLAIN}, then try again.\n";
-
-  else
-    printf "${MAGENTA}Syncing assets with S3...${PLAIN}";
-    mkdir -p $PUBLIC_ASSETS_DIR
-    rm -rf $PUBLIC_ASSETS_DIR/*
-    unzip -qq target/docker/stage/opt/docker/lib/ellipsis.ellipsis-1.0-SNAPSHOT-assets.jar -d $PUBLIC_ASSETS_DIR/
-    aws --profile $AWS_ELLIPSIS_PROFILE s3 sync $PUBLIC_ASSETS_DIR/public s3://$ASSETS_BUCKET/ --acl=public-read --quiet
-    S3_KEY=`date +'%Y-%m-%d'`-$BUNDLE
-    printf "${MAGENTA}Uploading ${GREEN}$BUNDLE${MAGENTA} to S3...${PLAIN}";
-    aws --profile $AWS_ELLIPSIS_PROFILE s3 cp $BUNDLE_PATH s3://$EB_BUCKET/$S3_KEY
-    aws --profile $AWS_ELLIPSIS_PROFILE elasticbeanstalk create-application-version \
-    --application-name "$APP_NAME" \
-    --version-label $VERSION_LABEL \
-    --source-bundle S3Bucket=$EB_BUCKET,S3Key=$S3_KEY \
-    --process;
-  fi
-fi
+printf "${MAGENTA}Uploading ${GREEN}$BUNDLE${MAGENTA} to S3...${PLAIN}\n";
+S3_KEY=`date +'%Y-%m-%d'`-$BUNDLE
+aws --profile $AWS_ELLIPSIS_PROFILE s3 cp $BUNDLE_PATH s3://$EB_BUCKET/$S3_KEY
+aws --profile $AWS_ELLIPSIS_PROFILE elasticbeanstalk create-application-version \
+--application-name "$APP_NAME" \
+--version-label $VERSION_LABEL \
+--source-bundle S3Bucket=$EB_BUCKET,S3Key=$S3_KEY \
+--process;
+printf "Done.\n";
 
 osascript -e "display notification \"The build script has ended.\" with title \"Build $VERSION_LABEL\" sound name \"Sosumi\""
 curl -f --data "message=🚀%20Build%20**${VERSION_LABEL}**%20is%20ready%20for%20deployment%20on%20${TARGET_ENV}.&responseContext=slack&channel=dev&token=${ELLIPSIS_DEPLOY_TOKEN}" https://bot.ellipsis.ai/api/say || (printf "${GREEN}Warning: the post-build announcement failed.${PLAIN}" && exit 1)
-printf "Done.\n\n"
+printf "\nDone!\n\n"
