Try to get assets syncing for stag01 again

diff --git a/deploy/circleci_build b/deploy/circleci_build
--- a/deploy/circleci_build
+++ b/deploy/circleci_build
@@ -143,25 +143,25 @@ zip -qq -r $BUNDLE_PATH .
 cd $TOP_DIR
 printf "\n${GREEN}OK.${PLAIN}\n"
 
+printf "\n\n${GREEN}Syncing assets with S3...${PLAIN}\n";
+printf "_____________________________________________________ \n";
+PUBLIC_ASSETS_DIR=/tmp/public-assets
+mkdir -p $PUBLIC_ASSETS_DIR
+rm -rf $PUBLIC_ASSETS_DIR/*
+unzip -qq target/docker/stage/opt/docker/lib/ellipsis.ellipsis-1.0-SNAPSHOT-assets.jar -d $PUBLIC_ASSETS_DIR/
+aws --profile $AWS_ELLIPSIS_PROFILE s3 sync $PUBLIC_ASSETS_DIR/public s3://assets-${ACCOUNT_ID}/ --acl=public-read --only-show-errors
 if [ "${TARGET_ENV}" = "prod" ]
 then
-  printf "\n\n${GREEN}Syncing assets with S3...${PLAIN}\n";
-  printf "_____________________________________________________ \n";
-  PUBLIC_ASSETS_DIR=/tmp/public-assets
-  mkdir -p $PUBLIC_ASSETS_DIR
-  rm -rf $PUBLIC_ASSETS_DIR/*
-  unzip -qq target/docker/stage/opt/docker/lib/ellipsis.ellipsis-1.0-SNAPSHOT-assets.jar -d $PUBLIC_ASSETS_DIR/
-  aws --profile $AWS_ELLIPSIS_PROFILE s3 sync $PUBLIC_ASSETS_DIR/public s3://assets-${ACCOUNT_ID}/ --acl=public-read --only-show-errors
   aws --profile $AWS_ELLIPSIS_PROFILE s3 sync $PUBLIC_ASSETS_DIR/public s3://ellipsis-assets/ --acl=public-read --only-show-errors
-  if [ $? -eq 0 ]
-  then
-    printf "${GREEN}OK.${PLAIN}\n";
-  else
-    printf "\n\n${RED}An error occurred!${PLAIN}\n";
-    announce_failure
-    printf "Bye.\n"
-    exit 1
-  fi
+fi
+if [ $? -eq 0 ]
+then
+  printf "${GREEN}OK.${PLAIN}\n";
+else
+  printf "\n\n${RED}An error occurred!${PLAIN}\n";
+  announce_failure
+  printf "Bye.\n"
+  exit 1
 fi
 
 printf "\n\n${GREEN}Uploading app bundle ${BUNDLE} to S3...${PLAIN}\n";
